import Link from "next/link";
import { PanelsTopLeft } from "lucide-react";
import { formatRelative } from "@/lib/utils";
import { TEMPLATE_LAYOUTS } from "@/lib/landing-sections";
import { pageContext } from "@/server/auth/session";
import { listLandingPages } from "@/server/services/landing-pages";
import { Badge, ButtonLink, DemoTag, EmptyState, EngineBadge, Mono, PageHeader, Panel, Table, Td, Th } from "@/components/admin/ui";

export const metadata = { title: "Landing pages" };

export default async function LandingPagesPage() {
  const ctx = await pageContext("products:read");
  const pages = await listLandingPages(ctx);
  return (
    <>
      <PageHeader
        eyebrow="Growth"
        title="Landing pages"
        description="Generated by the Landing Page Agent from templates A–E, edited section by section. Drafts stay private until you publish."
      />
      <div className="mb-6 grid gap-3 md:grid-cols-5">
        {Object.entries(TEMPLATE_LAYOUTS).map(([k, t]) => (
          <div key={k} className="rounded-lg border border-edge bg-panel p-4">
            <p className="text-sm font-medium text-fog">{t.label}</p>
            <p className="mt-1 text-xs text-dim">{t.description}</p>
          </div>
        ))}
      </div>
      <Panel bodyClassName="p-0">
        {pages.length ? (
          <Table minWidth={960}>
            <thead>
              <tr>
                <Th>Page</Th>
                <Th>Product</Th>
                <Th>Template</Th>
                <Th>Status</Th>
                <Th>Engine</Th>
                <Th>Updated</Th>
                <Th align="end" />
              </tr>
            </thead>
            <tbody>
              {pages.map(({ page, productTitle }) => (
                <tr key={page.id} className="hover:bg-panel-2/50">
                  <Td>
                    <Link href={`/admin/landing-pages/${page.id}`} className="font-medium text-fog hover:underline">
                      {page.headline}
                    </Link>
                    <div className="mt-0.5">
                      <Mono>/lp/{page.slug}</Mono>
                    </div>
                  </Td>
                  <Td>
                    <Link href={`/admin/products/${page.productId}`} className="text-haze hover:underline">
                      {productTitle}
                    </Link>{" "}
                    {page.isDemo && <DemoTag />}
                  </Td>
                  <Td className="text-xs">{TEMPLATE_LAYOUTS[page.template].label}</Td>
                  <Td>
                    <Badge tone={page.status === "PUBLISHED" ? "good" : page.status === "ARCHIVED" ? "neutral" : "info"}>{page.status.toLowerCase()}</Badge>
                  </Td>
                  <Td>
                    <EngineBadge method={page.generationMethod} model={page.model} />
                  </Td>
                  <Td className="text-xs">{formatRelative(page.updatedAt)}</Td>
                  <Td align="end">
                    <div className="flex justify-end gap-1">
                      {page.status === "PUBLISHED" && (
                        <ButtonLink href={`/lp/${page.slug}`} external size="sm" variant="ghost">
                          View
                        </ButtonLink>
                      )}
                      <ButtonLink href={`/admin/landing-pages/${page.id}`} size="sm">
                        Edit
                      </ButtonLink>
                    </div>
                  </Td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          <div className="p-5">
            <EmptyState icon={PanelsTopLeft} title="No landing pages yet">
              Open a product and generate one (Landing tab), or run a launch kit.
            </EmptyState>
          </div>
        )}
      </Panel>
    </>
  );
}
