// DEMO discovery pool — fictional-but-plausible candidates used ONLY in DEMO_MODE.
// Every value here is DEMO provenance and is labelled as such throughout the UI.

import type { DiscoveredProduct } from "./types";

const demo = (p: Omit<DiscoveredProduct, "provenance" | "sourceLabel" | "currency"> & { currency?: string }): DiscoveredProduct => ({
  currency: "USD",
  ...p,
  provenance: "DEMO",
  sourceLabel: "Demo discovery feed",
});

export const DEMO_DISCOVERY_POOL: DiscoveredProduct[] = [
  demo({
    sourceProductId: "demo-disc-001",
    title: "Collapsible Silicone Food Storage Set",
    category: "Home & Kitchen",
    description: "Stackable containers that fold flat when empty, so the cupboard stays usable.",
    problemSolved: "a cupboard avalanche of mismatched plastic containers",
    targetAudience: "small-kitchen cooks and meal-preppers",
    highlights: ["Folds to about a quarter of its height when empty", "Set of 4 sizes with snap-lock lids"],
    sellingPrice: 29.99,
    cost: 7.4,
    shippingCost: 3.2,
    shippingDaysMin: 7,
    shippingDaysMax: 12,
    businessModel: "DROPSHIPPING",
    trendScore: 62,
    competitionScore: 58,
    contentScore: 78,
    impulseScore: 70,
    problemScore: 74,
    noveltyScore: 52,
    tags: ["kitchen", "storage", "meal prep"],
    trendKeyword: "Food storage container",
  }),
  demo({
    sourceProductId: "demo-disc-002",
    title: "Magnetic Spice Rack Tins (12-Pack)",
    category: "Home & Kitchen",
    description: "Clear-lid magnetic tins that stick to the fridge or a steel panel.",
    problemSolved: "digging through a crowded spice drawer",
    targetAudience: "home cooks with limited counter space",
    highlights: ["Clear lids show what's inside", "Strong magnetic base"],
    sellingPrice: 32,
    commissionPercentage: 8,
    businessModel: "AFFILIATE",
    trendScore: 55,
    competitionScore: 45,
    contentScore: 72,
    impulseScore: 64,
    problemScore: 68,
    noveltyScore: 60,
    tags: ["kitchen", "organisation"],
  }),
  demo({
    sourceProductId: "demo-disc-003",
    title: "Clip-On Laptop Privacy Screen",
    category: "Tech Accessories",
    description: "Magnetic privacy filter that darkens the screen from side angles.",
    problemSolved: "strangers reading your screen on trains and in cafés",
    targetAudience: "remote workers and commuters",
    highlights: ["Attaches magnetically, no adhesive", "Reversible matte/gloss side"],
    sellingPrice: 39.99,
    commissionPercentage: 6,
    businessModel: "AFFILIATE",
    trendScore: 58,
    competitionScore: 52,
    contentScore: 66,
    impulseScore: 55,
    problemScore: 70,
    noveltyScore: 48,
    tags: ["laptop", "privacy", "remote work"],
  }),
  demo({
    sourceProductId: "demo-disc-004",
    title: "Self-Cleaning Pet Grooming Brush",
    category: "Pets",
    description: "Retractable-pin slicker brush — press a button and the fur slides off.",
    problemSolved: "pet hair clumps stuck in the brush after every groom",
    targetAudience: "dog and cat owners",
    highlights: ["One-button hair release", "Rounded pins for sensitive skin"],
    sellingPrice: 19.99,
    cost: 4.1,
    shippingCost: 2.6,
    shippingDaysMin: 6,
    shippingDaysMax: 11,
    businessModel: "DROPSHIPPING",
    trendScore: 66,
    competitionScore: 72,
    contentScore: 88,
    impulseScore: 82,
    problemScore: 80,
    noveltyScore: 44,
    saturationScore: 68,
    tags: ["pets", "grooming"],
    trendKeyword: "Pet grooming",
  }),
  demo({
    sourceProductId: "demo-disc-005",
    title: "Under-Cabinet Motion Sensor Light Bar",
    category: "Home & Kitchen",
    description: "Rechargeable LED strip that turns on when you walk past and off when you leave.",
    problemSolved: "fumbling in a dark cupboard or hallway at night",
    targetAudience: "renters who can't hard-wire lighting",
    highlights: ["USB-C rechargeable", "Magnetic mount — no drilling"],
    sellingPrice: 24.99,
    cost: 6.2,
    shippingCost: 2.9,
    shippingDaysMin: 7,
    shippingDaysMax: 13,
    businessModel: "DROPSHIPPING",
    trendScore: 60,
    competitionScore: 64,
    contentScore: 84,
    impulseScore: 78,
    problemScore: 72,
    noveltyScore: 50,
    tags: ["lighting", "renter friendly"],
  }),
  demo({
    sourceProductId: "demo-disc-006",
    title: "Car Trunk Collapsible Organizer",
    category: "Car & Travel",
    description: "Divided trunk box that folds flat and stops groceries sliding around.",
    problemSolved: "groceries rolling around the boot on every corner",
    targetAudience: "commuters and families with cars",
    highlights: ["Folds flat when not in use", "Non-slip base with side pockets"],
    sellingPrice: 34.99,
    commissionPercentage: 7,
    businessModel: "AFFILIATE",
    trendScore: 48,
    competitionScore: 60,
    contentScore: 70,
    impulseScore: 58,
    problemScore: 66,
    noveltyScore: 38,
    tags: ["car", "organisation"],
  }),
];
